config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :users do 
    resources :appointments
  end
  resources :appointments

  root 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user
    belongs_to :employee

    validates :time, uniqueness: true 

    validate :valid_time
    scope :chrono, -> {order(:time)}
    scope :reverse_chrono, -> {order(:time).reverse_order}

    def valid_time
        if time.hour < 5 || time.hour > 19.5
            errors.add(:time, "hour must be between 5am and 7:30pm")
        end
        if time.strftime("%M") != "00" && time.strftime("%M") != "30"
            errors.add(:time, "minute of hour must be 00 or 30")
        end 
        if time <= Time.now 
            errors.add(:time, "must be booked a day in advance")
        end
    end

    #def self.chronological
    #    self.order('(appointments.time) asc')
    #end

end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :appointments
    has_many :users, through: :appointments
    has_many :employee_times

    validates :name, presence: true
end

app/models/employee_time.rb
class EmployeeTime < ApplicationRecord
    belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
    has_many :appointments
    has_many :employees, through: :appointments

    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true 
    validates :password, confirmation: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    ### HELPER_METHOD MAKES METHOD AVAILABLE TO VIEWS TOO ###
    helper_method :current_user, :authorize, :logged_in?, :is_users_appointment?

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        end 
    end

    ### USED??? ###
    def authorize
        if current_user.nil? 
            flash[:notice] = "You must be logged in to access this page."
            redirect_to login_path
        end
    end

    ### USED??? ###
    def is_users_appointment?(appointment)
        current_user.id == appointment.user_id
    end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def new 
        @appointment = Appointment.new(user_id: params[:user_id])
    end

    def create 
        @appointment = Appointment.new(appointment_params)
        if @appointment.save 
            if logged_in?
                if is_users_appointment?(@appointment)
                    flash[:notice] = "Training Session Successfully Booked."
                    redirect_to user_appointment_path(@appointment.user_id, @appointment.id)
                end
            end 
        else
            render :new 
        end
    end

    def show
        get_appointment_and_user
    end

    def edit 
        get_appointment_and_user
    end


    ### LATER: MAKE TO WHERE A USER CANNOT UPDATE AN OLD TRAINING SESSION ###
    def update 
        @appointment = Appointment.find(params[:id])
        if @appointment.update(appointment_params)
            if logged_in?
                if is_users_appointment?(@appointment)
                    flash[:notice] = "Training Session Updated Successfully."
                    redirect_to appointment_path(@appointment.id)
                end 
            end 
        else 
            render :edit
        end
    end

    def destroy 
        @appointment = Appointment.find(params[:id])
        if logged_in?
            if is_users_appointment?(@appointment)
                @appointment.destroy 
                flash[:notice] = "Training Session Successfully Canceled."
                redirect_to root_path
            end 
        end 
    end

    def index
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            if @user.nil?
                flash[:notice] = "User not found."
                redirect_to root_path
            else
                @appointments = @user.appointments.reverse_chrono.where('time < ?', Time.now)
            end
        else
            @appointments = Appointment.chrono.where('time > ?', Time.now)
        end
    end

    private 

    def appointment_params 
        params.require(:appointment).permit(:time, :user_id, :employee_id)
    end

    def get_appointment_and_user
        @appointment = Appointment.find_by(id: params[:id])
        @user = User.find_by(id: @appointment.user_id)
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new 
    end

    def create
        ### IF USER USED OMNIAUTH ###
        if auth
            @user = User.find_or_create_by(uid: auth['uid']) do |u|
                u.name = auth['info']['name']
                u.email = auth['info']['email']
            end 
            @user.password = SecureRandom.hex
            if @user.save 
                session[:user_id] = @user.id
                flash[:notice] = "You're in."
                render 'users/index'
            else 
                flash[:notice] = "Something went wrong."
                redirect_to root_path
            end 
        ### IF USER USED EMAIL ###
        else 
            @user = User.find_by(email: params[:email].downcase)
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id 
                flash[:notice] = "Log In Successful"
                redirect_to root_path
            else 
                flash[:notice] = "Could not find account!"
                render :new 
            end
        end 
    end

    def destroy 
        if session[:user_id]
            reset_session
            ### THIS BETTER WORK ### 
            if session[:user_id] == nil
                flash[:notice] = "You're logged out."
                redirect_to '/login'
            end 
        else 
            flash[:notice] = "No one is logged in."
            redirect_to '/login'
        end 
    end

    private 

    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController 
    
    def facebook 
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new 
        @user = User.new
    end

    def create 
        @user = User.new(user_params)
        @user.email.downcase!
        if @user.save
            session[:user_id] = @user.id 
            flash[:notice] = "You're in."
            redirect_to root_path
        else 
            flash[:notice] = "Couldn't create account!"
            render :new 
        end
    end

    def index
        @user = current_user
    end

    def edit
        @user = current_user
    end

    def update
        @user = current_user
        if @user.update(user_params)
            if logged_in?
                flash[:notice] = "User Profile Updated Successfully."
                redirect_to root_path
            end
        else
            flash[:notice] = "Something went wrong, please try again!"
            render :edit
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private 

    def user_params 
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def convert_time(datetime_object)
        datetime_object.strftime("%A, %B %e, %Y at %I:%M %p")
    end

    def button_text
        if controller.action_name == "new"
           return "sign up"
        elsif controller.action_name == "edit"
           return "update"
        else
           return "submit"
        end
    end
    
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/appointments/_appt.html.erb
<% @appointments.each do |appointment| %>
    <div class="text">
        <strong>Coach:</strong> <%= appointment.employee.name %><br>
        <strong>Time:</strong> <%= convert_time(appointment.time) %><br>
        <strong>Client:</strong> <%= appointment.user.name %><br><br><br>
    </div>
<% end %>

app/views/appointments/_errors.html.erb
<% if @appointment.errors.any? %> 
    <div id="error_explanation">
        <h2> There were some errors: </h2> 
        <ul> 
            <% @appointment.errors.full_messages.each do |message| %> 
                <li> <%= message %> </li>  
            <% end %> 
        </ul> 
    </div> 
<% end %> 

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
    <%= f.hidden_field :user_id %> 
    <h3> Choose Your Coach </h3>
    <%= f.collection_select :employee_id, Employee.all, :id, :name %><br><br><br><br> 

    <h3> Choose A Time </h3> 

    <%= render 'time' %> 

    <div class="field <%= ' field_with_errors' if @appointment.errors[:time].any? %>">
        <%= f.datetime_select :time, { ampm: true, use_short_month: true, start_year: 2020, start_hour: 5, end_hour: 19, minute_step: 30, order: [:month, :day, :year, :hour, :minute ] }, {class: "form-control" } %> 
    </div>
    <br><br><br><br><br>

    <%= f.submit "submit" %> 
<% end %> 

app/views/appointments/_time.html.erb
<ul>
    <li> First training session starts at 5am </li>
    <li> Last training session starts at 7:30pm </li> 
    <li> All training sessions start every half hour </li> 
</ul>

app/views/appointments/edit.html.erb
<% if logged_in? %> 
    <% if is_users_appointment?(@appointment) %> 
        <%= render 'errors' %> 
        <h1> Update Appointment </h1> 

        <%= render 'form' %>

    <% end %> 
<% end %> 

app/views/appointments/index.html.erb
<% if @user %>
    <% if @user.appointments.empty? %>
        <%= @user.name %> has not booked any training sessions yet.
    <% else %>
        <%= render 'appt' %>
    <% end %>
<% else %>
    <%= render 'appt' %>
<% end %>

app/views/appointments/new.html.erb
<% if logged_in? %> 
    <% if is_users_appointment?(@appointment) %> 
        <%= render 'errors' %>
        <h1> Book a Training Session </h1> 

        <%= render 'form' %>

    <% end %> 
<% end %>

app/views/appointments/show.html.erb
<div class="text">
    <strong>Coach:</strong> <%= @appointment.employee.name %><br> 
    <strong>Time:</strong> <%= convert_time(@appointment.time) %><br> 
    <strong>Client Name:</strong> <%= @user.name %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coaching Manager (Appointment Manager System)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="text">
    Coaching Manager // 
    <% if current_user %>
      <!-- current_user will return true if a user is logged in -->
      <%= "Logged in as #{current_user.email}" %> • <%= link_to 'Home', root_path %> • <%= link_to 'Profile', user_path(current_user) %> • <%= link_to 'All Sessions', appointments_path %> • <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <!-- not logged in -->
      <%= link_to 'Home', root_path %> • <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
    <% end %>
    <hr>
    </div>

    <% if flash[:notice] %> 
      <%= flash[:notice] %> 
    <% end %> <br>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="text">
        <%= f.label :name %> 
        <%= f.text_field :name %><br>

        <%= f.label :email %> 
        <%= f.text_field :email %><br>

        <%= f.label :password %> 
        <%= f.password_field :password %><br>

        <%= f.label :password_confirmation %> 
        <%= f.password_field :password_confirmation %><br>

        <%= f.submit button_text %> 
    </div>
<% end %> 

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% if @user %> <br> 
    <div class="text">
        <strong>Name:</strong> <%= @user.name %><br> 
        <strong>Email:</strong> <%= @user.email %><br><br>
    </div>
    <div class="new_appt">
        <%= link_to "book a new training session", new_user_appointment_path(@user.id) %> 
    </div><br><br><br> 
    <% if @user.appointments %> 
        <h3> Your Next Training Session: </h3>
        <% if @user.appointments.empty? %>
            <div class="text">
                You currently do not have any training sessions booked.
            </div>
        <% else %>
            <% @user.appointments.where('time > ?', Time.now).limit(1).each do |appointment| %>
                <div class="text">
                    <strong>Coach:</strong> <%= appointment.employee.name %><br>
                    <strong>Time:</strong> <%= convert_time(appointment.time) %><br><br>
                </div>
                <%= link_to "edit session", edit_user_appointment_path(@user.id, appointment.id) %><br><br>
                <%= button_to "cancel session", appointment, method: :delete %>  
                <br><br><br><br><br> 
            <% end %> 
        <% end %> 
    <% end %> 
<% elsif @user == nil %> 
    <div class="link">
        <%= link_to "Continue with Facebook", '/auth/facebook' %>
    </div>
    <br>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<br><br><br>
<div class="text">
    or 
</div><br> 
<div class="link">
    <%= link_to "Continue with Facebook", '/auth/facebook' %>
</div>

app/views/users/show.html.erb
<div class="text">
    <strong>Name:</strong> <%= @user.name %><br> 
    <strong>Email:</strong> <%= @user.email %><br><br>
</div>

<% if @user == current_user %>
    <div class="link">
        <%= link_to "edit profile", edit_user_path(@user.id) %>
    </div><br><br><br> 

    <div class="new_appt">
        <%= link_to "book a new training session", new_user_appointment_path(@user.id) %> 
    </div><br><br><br>
<% end %>

<% if @user.appointments %> 
    <h3> Booked Training Sessions: </h3>
    <%= link_to 'Past Training Sessions', user_appointments_path(@user.id) %><br><br><br>
    <% if @user.appointments.empty? %>
        <div class="text">
            <%= @user.name %> does not have any training sessions currently booked.
        </div>
    <% else %>
        <% @user.appointments.where('time > ?', Time.now).each do |appointment| %>
            <div class="text">
                <strong>Coach:</strong> <%= appointment.employee.name %><br>
                <strong>Time:</strong> <%= convert_time(appointment.time) %><br><br>
            </div>

            <% if @user == current_user %>
            <div>
                <%= link_to "edit session", edit_user_appointment_path(@user.id, appointment.id) %><br><br>
                <%= button_to "cancel session", appointment, method: :delete %> 
            </div>
                <br><br><br><br><br>
            <% end %>
             
        <% end %> 
    <% end %> 
<% end %> 

app/views/welcome/home.html.erb
<% if @user %> <br> 
    <div class="text">
        <strong>Name:</strong> <%= @user.name %> <br> 
        <strong>Email:</strong> <%= @user.email %> <br> <br> 
    </div>
    <div class="new_appt">
        <%= link_to "book a new training session", new_user_appointment_path(@user.id) %> 
    </div><br><br><br> 
    <% if @user.appointments %> 
        <h3> Your Training Sessions: </h3>
        <% if @user.appointments.empty? %>
            <div class="text">
                You currently do not have any training sessions.
            </div>
        <% else %>
            <% @user.appointments.each do |appointment| %>
                <div class="text">
                    <strong>Coach:</strong> <%= appointment.employee.name %><br>
                    <strong>Time:</strong> <%= convert_time(appointment.time) %><br>
                </div>
                <div class="link">
                    <%= link_to "edit session", edit_user_appointment_path(@user.id, appointment.id) %> 
                </div><br>
                <%= button_to "cancel session", appointment, method: :delete %> 
                <br><br><br><br><br> 
            <% end %> 
        <% end %> 
    <% end %> 
<% elsif @user == nil %> 
    <div class="link">
        <%= link_to "Continue with Facebook", '/auth/facebook' %>
    </div>
    <br>
<% end %>